# Generated by Django 4.2.5 on 2023-09-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_check', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='answer',
            new_name='answer1',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='question',
            new_name='answer10',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer11',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer3',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer4',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer5',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer6',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer7',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer8',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer9',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
